### ISSUE TITLE
Why does the line augmentation require/use Ground Truth?

### ISSUE THREAD

**Issue by wrznr** [maxnth/LineAug#1]
Shouldn't it work on the images alone?

**Comment by maxnth** [comment]
The line augmentation works on images alone and the `--ground_truth` parameter is only optional (all it does is "mapping" existing ground truth files to the augmented line images by creating a new text file with the same output name as the augmented line image). 
Running `augment.py` normally should work without setting the parameter.

The help text isn't very clear on this and I should probably change it.
